### ISSUE TITLE
Incorrect handling query parameters containing semicolons

### ISSUE THREAD

**Issue by rigens** [encode/starlette#1325]
### Describe the bug

It seems Starlette treats the semicolon as a parameter separator, which is incorrect. IMHO, this is a critical bug that makes it impossible to use Starlette in many scenarios. Other web frameworks (flask, aiohttp, ...) handle semicolons correctly

### To reproduce

```python
from starlette.testclient import TestClient
from starlette.requests import Request
from starlette.applications import Starlette
from starlette.routing import Route
from starlette.responses import PlainTextResponse

param_value = 'a;b;c'
url = f'/test?param={param_value}'


async def test_route(request: Request):
    param = request.query_params['param']  
    # param is 'a' 
    # request.query_params.keys() is ['param', 'b', 'c']
    assert param == param_value  # Assertion failed
    return PlainTextResponse(param)


app = Starlette(debug=True, routes=[Route('/test', test_route)])

client = TestClient(app)

response = client.request(url=url, method='GET')
```

### Environment

- OS: Ubuntu 20.04
- Python version: 3.9.1
- Starlette version:  0.16.0

**Comment by Kludex** [comment]
Hmm... I can't reproduce it. Looks alright here :thinking: 

Am I missing something?

**Comment by rigens** [comment]
> Am I missing something?

Maybe starlette version? The code above fails with AssertionError on Python 3.7-3.9, Ubuntu 20.04, Windows 8.1, Starlette 0.16.0

**Comment by Kludex** [comment]
I don't have your results... Can you check https://github.com/encode/starlette/pull/1326/ and suggest modification to reproduce?

**Comment by rigens** [comment]
It was urllib related issue. It has been fixed for security reasons in February 2021 (https://python-security.readthedocs.io/vuln/urllib-query-string-semicolon-separator.html). I tested it on older Python versions.
