### ISSUE TITLE
[Feature requests] Get route method in middlewares

### ISSUE THREAD

**Issue by amitripshtos** [encode/starlette#238]
Hey,
I'm working on a JWT autentication package for starlette, and I'm having few diffuculties on implementing it well:

1. When I decode the token, I want to "inject" the token's payload into the Request object. Currently the SessionMiddleware adds it to the scope, so currently i'm doing something like this:
```
request._scope['session'] = my_payload_dict
```
I wanted to add non-dict data to the Request's scope, in a way the IDE won't have issues with (since request.session is a method that returns a dictionary)

2. When I get a request in the middleware, I would like to get also the function which the Request is going to - since I want to add decorator to every route method:
```
@app.route('/')
@anonymous_allowed
def hello_world(request: Request):
    ....
```

I'm working on that git:
https://github.com/amitripshtos/starlette-jwt

What is the best way to achieving these 2 things in starlette, in your perspective?
Thanks,
Amit.

**Comment by amitripshtos** [comment]
At the end I just save a dictionary to the request.session using the scope, so that's fine.
However I still think it's hard to have a middleware that have special cases for specific routes and I took a look at starlette code but could not find any way to do this 

It would be great if you guys take a look at my project , and give some guidance regarding the following issues (I just published a alpha version that works)

Thanks for making this library, I'm really enjoying using it and writing to it! :)
Amit.

**Comment by lovelydinosaur** [comment]
For view-level cases, write decorators that wrap the request/response interface, rather than ASGI middleware.

I’ll try to take a look at your package soon, and see what else we can be doing here.

**Comment by amitripshtos** [comment]
Is there any example for warpping the request interface ? Maybe in the unit tests

**Comment by steinnes** [comment]
I'm interested in this as well.  I wrote a rather hacky jwt-based authentication wrapper for my own needs, where I replace the request object with one which has a `user` attribute which is populated by my wrapper, done in a rather complicated way where I actually hook into the asgi interface and replace the Request object with my own chimera which also contains the user.

Since then I was thinking to do something cleaner, which essentially would wrap the request/response interface, and pass on the auth data as a kwarg.  Something akin to:

```python
def auth(required=False):
    def inner(func):
        @functools.wraps(func)
        def wrapper(req, *args, **kwargs):
            token = req.headers.get('authorization', '').replace('Bearer ', '')
            if not token and required:
                raise AuthenticationRequired('Invalid or missing auth header')
            try:
                decoded = decode(token, secret)
            except InvalidTokenException as e:
                if required:
                    raise AuthenticationRequired(str(e))
                decoded = None
            kwargs.update('auth', decoded)
            return func(req, *args, **kwargs)
        return wrapper
    return inner

# usage
@app.route("/")
@auth(required=False)
def serve_index(auth=None):
    if auth and 'user_id' in auth:
        user = User.query.get(auth['user_id']).first()
        return JSONResponse(serialize_user_docs(user))
    return JSONResponse(serialize_public_docs())

```

@tomchristie is this along the lines you were thinking with request/response interface?

**Comment by steinnes** [comment]
Thanks, looking forward to updating and refactoring mine to fit with this 👍 

edit: (or simply start using `starlette-jwt` =) )

**Comment by amitripshtos** [comment]
Looks good! Thanks
