### ISSUE TITLE
Lifespan

### ISSUE THREAD

**Issue by rajeev** [encode/starlette#372]
I'm a bit confused by the concept of Lifespan. From uvicorn, a lifespan is the lifecycle of the entire app (as opposed to a request-response lifecycle, which seems to be handled by http startup/shutdown scope).

However, in starlette DatabaseMiddleware I saw an option "rollback_on_shutdown" which is executed on the lifespan shutdown. Shouldn't that be specific to each request/response? Why does starlette rollback the active transaction when the app itself is dying, rather than when a request-response cycle fails/dies?

On a sidenote, does starlette have a slack or gitter community?

**Comment by rajeev** [comment]
@tomchristie are you saying then, that the rollback_on_shutdown is specifically for writing test cases?

**Comment by lovelydinosaur** [comment]
Yes, that's the only reason you'd want to use it.
I think that's clear in the docs, but perhaps it needs a code comment too.
